# Generated by Django 2.2.7 on 2019-12-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('shoeSize', models.IntegerField()),
                ('gender', models.CharField(default='Null', max_length=10)),
            ],
        ),
    ]
